In [1]:
# Importing libraries and data set

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

In [2]:
path = r'C:\Users\jmowe\OneDrive\Project 6 CF'

In [3]:
df = pd.read_csv(os.path.join(path, 'Data', 'US_Accidents_March23.csv'))

In [4]:
df.shape

(7728394, 46)

In [5]:
df.head()

ID   Source  Severity           Start_Time             End_Time  \
0  A-1  Source2         3  2016-02-08 05:46:00  2016-02-08 11:00:00   
1  A-2  Source2         2  2016-02-08 06:07:59  2016-02-08 06:37:59   
2  A-3  Source2         2  2016-02-08 06:49:27  2016-02-08 07:19:27   
3  A-4  Source2         3  2016-02-08 07:23:34  2016-02-08 07:53:34   
4  A-5  Source2         2  2016-02-08 07:39:07  2016-02-08 08:09:07   

   Start_Lat  Start_Lng  End_Lat  End_Lng  Distance(mi)  ... Roundabout  \
0  39.865147 -84.058723      NaN      NaN          0.01  ...      False   
1  39.928059 -82.831184      NaN      NaN          0.01  ...      False   
2  39.063148 -84.032608      NaN      NaN          0.01  ...      False   
3  39.747753 -84.205582      NaN      NaN          0.01  ...      False   
4  39.627781 -84.188354      NaN      NaN          0.01  ...      False   

  Station   Stop Traffic_Calming Traffic_Signal Turning_Loop Sunrise_Sunset  \
0   False  False           False          False        False          Night   
1   False  False           False          False        False          Night   
2   False  False           False           True        False          Night   
3   False  False           False          False        False          Night   
4   False  False           False           True        False            Day   

  Civil_Twilight Nautical_Twilight Astronomical_Twilight  
0          Night             Night                 Night  
1          Night             Night                   Day  
2          Night               Day                   Day  
3            Day               Day                   Day  
4            Day               Day                   Day  

[5 rows x 46 columns]

In [6]:
df.columns.values

array(['ID', 'Source', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat',
       'Start_Lng', 'End_Lat', 'End_Lng', 'Distance(mi)', 'Description',
       'Street', 'City', 'County', 'State', 'Zipcode', 'Country',
       'Timezone', 'Airport_Code', 'Weather_Timestamp', 'Temperature(F)',
       'Wind_Chill(F)', 'Humidity(%)', 'Pressure(in)', 'Visibility(mi)',
       'Wind_Direction', 'Wind_Speed(mph)', 'Precipitation(in)',
       'Weather_Condition', 'Amenity', 'Bump', 'Crossing', 'Give_Way',
       'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station', 'Stop',
       'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop',
       'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'], dtype=object)

In [7]:
# Print the column names
print(df.columns)


Index(['ID', 'Source', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat',
       'Start_Lng', 'End_Lat', 'End_Lng', 'Distance(mi)', 'Description',
       'Street', 'City', 'County', 'State', 'Zipcode', 'Country', 'Timezone',
       'Airport_Code', 'Weather_Timestamp', 'Temperature(F)', 'Wind_Chill(F)',
       'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Direction',
       'Wind_Speed(mph)', 'Precipitation(in)', 'Weather_Condition', 'Amenity',
       'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway',
       'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal',
       'Turning_Loop', 'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'],
      dtype='object')


In [8]:
#Turning_Loop has only 1 unique value so dropping it

unique_values = df['Turning_Loop'].unique()
print(unique_values)

[False]


In [9]:
df = df.drop('Turning_Loop', axis=1)

In [10]:
df.Severity

0          3
1          2
2          2
3          3
4          2
          ..
7728389    2
7728390    2
7728391    2
7728392    2
7728393    2
Name: Severity, Length: 7728394, dtype: int64

In [11]:
df.Severity.values

array([3, 2, 2, ..., 2, 2, 2], dtype=int64)

In [12]:
column_name = 'Severity'
column_values = df[column_name]
print(column_values)

0          3
1          2
2          2
3          3
4          2
          ..
7728389    2
7728390    2
7728391    2
7728392    2
7728393    2
Name: Severity, Length: 7728394, dtype: int64


In [13]:
df.Severity.max()

4

In [14]:
df.Weather_Timestamp.values

array(['2016-02-08 05:58:00', '2016-02-08 05:51:00',
       '2016-02-08 06:56:00', ..., '2019-08-23 18:53:00',
       '2019-08-23 18:51:00', '2019-08-23 20:50:00'], dtype=object)

In [15]:
df.Weather_Condition.values

array(['Light Rain', 'Light Rain', 'Overcast', ..., 'Partly Cloudy',
       'Fair', 'Fair'], dtype=object)

In [16]:
df.Amenity.values

array([False, False, False, ..., False, False, False])

In [17]:
df.Bump.values

array([False, False, False, ..., False, False, False])

In [18]:
df.Crossing.values

array([False, False, False, ..., False, False, False])

In [19]:
df.count()

ID                       7728394
Source                   7728394
Severity                 7728394
Start_Time               7728394
End_Time                 7728394
Start_Lat                7728394
Start_Lng                7728394
End_Lat                  4325632
End_Lng                  4325632
Distance(mi)             7728394
Description              7728389
Street                   7717525
City                     7728141
County                   7728394
State                    7728394
Zipcode                  7726479
Country                  7728394
Timezone                 7720586
Airport_Code             7705759
Weather_Timestamp        7608166
Temperature(F)           7564541
Wind_Chill(F)            5729375
Humidity(%)              7554250
Pressure(in)             7587715
Visibility(mi)           7551296
Wind_Direction           7553188
Wind_Speed(mph)          7157161
Precipitation(in)        5524808
Weather_Condition        7554935
Amenity                  7728394
Bump      

In [20]:
df.isnull().sum()

ID                             0
Source                         0
Severity                       0
Start_Time                     0
End_Time                       0
Start_Lat                      0
Start_Lng                      0
End_Lat                  3402762
End_Lng                  3402762
Distance(mi)                   0
Description                    5
Street                     10869
City                         253
County                         0
State                          0
Zipcode                     1915
Country                        0
Timezone                    7808
Airport_Code               22635
Weather_Timestamp         120228
Temperature(F)            163853
Wind_Chill(F)            1999019
Humidity(%)               174144
Pressure(in)              140679
Visibility(mi)            177098
Wind_Direction            175206
Wind_Speed(mph)           571233
Precipitation(in)        2203586
Weather_Condition         173459
Amenity                        0
Bump      

In [21]:
#Checking for dups, no dups found
df_dups = df[df.duplicated()]

In [22]:
df_dups

Empty DataFrame
Columns: [ID, Source, Severity, Start_Time, End_Time, Start_Lat, Start_Lng, End_Lat, End_Lng, Distance(mi), Description, Street, City, County, State, Zipcode, Country, Timezone, Airport_Code, Weather_Timestamp, Temperature(F), Wind_Chill(F), Humidity(%), Pressure(in), Visibility(mi), Wind_Direction, Wind_Speed(mph), Precipitation(in), Weather_Condition, Amenity, Bump, Crossing, Give_Way, Junction, No_Exit, Railway, Roundabout, Station, Stop, Traffic_Calming, Traffic_Signal, Sunrise_Sunset, Civil_Twilight, Nautical_Twilight, Astronomical_Twilight]
Index: []

[0 rows x 45 columns]

In [23]:
#Identifying true/false columns
boolean_columns = df.select_dtypes(include=bool).columns
print(boolean_columns)

Index(['Amenity', 'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit',
       'Railway', 'Roundabout', 'Station', 'Stop', 'Traffic_Calming',
       'Traffic_Signal'],
      dtype='object')


In [24]:
#Changing True/False to 1/0
for column in boolean_columns:
    if df[column].dtype == bool:
        df[column] = df[column].astype(int)

In [25]:
#Checking mixed-type columns

for col in df.columns.tolist():
      weird = (df[[col]].applymap(type) != df[[col]].iloc[0].apply(type)).any(axis = 1)
      if len (df[weird]) > 0:
        print (col)


Description
Street
City
Zipcode
Timezone
Airport_Code
Weather_Timestamp
Wind_Direction
Weather_Condition
Sunrise_Sunset
Civil_Twilight
Nautical_Twilight
Astronomical_Twilight


In [26]:
unique_values = df['Civil_Twilight'].unique()
print(unique_values)

['Night' 'Day' nan]


In [27]:
#Making new dataset with all missing values dropped

df_clean = df.dropna()

In [28]:
df_clean.count()

ID                       3554549
Source                   3554549
Severity                 3554549
Start_Time               3554549
End_Time                 3554549
Start_Lat                3554549
Start_Lng                3554549
End_Lat                  3554549
End_Lng                  3554549
Distance(mi)             3554549
Description              3554549
Street                   3554549
City                     3554549
County                   3554549
State                    3554549
Zipcode                  3554549
Country                  3554549
Timezone                 3554549
Airport_Code             3554549
Weather_Timestamp        3554549
Temperature(F)           3554549
Wind_Chill(F)            3554549
Humidity(%)              3554549
Pressure(in)             3554549
Visibility(mi)           3554549
Wind_Direction           3554549
Wind_Speed(mph)          3554549
Precipitation(in)        3554549
Weather_Condition        3554549
Amenity                  3554549
Bump      

In [29]:
df_clean.head()

ID   Source  Severity           Start_Time  \
3402762  A-3412645  Source1         3  2016-02-08 00:37:08   
3402767  A-3412650  Source1         3  2016-02-08 07:53:43   
3402771  A-3412654  Source1         2  2016-02-08 11:51:46   
3402773  A-3412656  Source1         2  2016-02-08 15:16:43   
3402774  A-3412657  Source1         2  2016-02-08 15:43:50   

                    End_Time  Start_Lat  Start_Lng    End_Lat    End_Lng  \
3402762  2016-02-08 06:37:08  40.108910 -83.092860  40.112060 -83.031870   
3402767  2016-02-08 13:53:43  39.172393 -84.492792  39.170476 -84.501798   
3402771  2016-02-08 17:51:46  41.375310 -81.820170  41.367860 -81.821740   
3402773  2016-02-08 21:16:43  40.109310 -82.968490  40.110780 -82.984000   
3402774  2016-02-08 21:43:50  39.192880 -84.477230  39.196150 -84.473350   

         Distance(mi)  ... Railway Roundabout Station Stop Traffic_Calming  \
3402762         3.230  ...       0          0       0    0               0   
3402767         0.500  ...       0          0       0    0               0   
3402771         0.521  ...       0          0       0    0               0   
3402773         0.826  ...       0          0       0    0               0   
3402774         0.307  ...       0          0       0    0               0   

        Traffic_Signal Sunrise_Sunset Civil_Twilight Nautical_Twilight  \
3402762              0          Night          Night             Night   
3402767              0            Day            Day               Day   
3402771              0            Day            Day               Day   
3402773              0            Day            Day               Day   
3402774              0            Day            Day               Day   

        Astronomical_Twilight  
3402762                 Night  
3402767                   Day  
3402771                   Day  
3402773                   Day  
3402774                   Day  

[5 rows x 45 columns]

In [30]:
#Checking mixed-type columns again in new data set

for col in df_clean.columns.tolist():
      weird = (df_clean[[col]].applymap(type) != df_clean[[col]].iloc[0].apply(type)).any(axis = 1)
      if len (df_clean[weird]) > 0:
        print (col)
        
        #No mixed-type columns now

In [31]:
unique_values = df_clean['Civil_Twilight'].unique()
print(unique_values)

['Night' 'Day']


In [32]:
#Changing Day and Night Values to Day=1 And Night=0

df_clean = df_clean.copy()
df_clean.loc[:, 'Sunrise_Sunset'] = df_clean['Sunrise_Sunset'].replace({'Day': 1, 'Night': 0})
df_clean.loc[:, 'Civil_Twilight'] = df_clean['Civil_Twilight'].replace({'Day': 1, 'Night': 0})
df_clean.loc[:, 'Astronomical_Twilight'] = df_clean['Astronomical_Twilight'].replace({'Day': 1, 'Night': 0})
df_clean.loc[:, 'Nautical_Twilight'] = df_clean['Nautical_Twilight'].replace({'Day': 1, 'Night': 0})


C:\Users\jmowe\AppData\Local\Temp\ipykernel_7540\2116477786.py:4: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_clean.loc[:, 'Sunrise_Sunset'] = df_clean['Sunrise_Sunset'].replace({'Day': 1, 'Night': 0})
C:\Users\jmowe\AppData\Local\Temp\ipykernel_7540\2116477786.py:5: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_clean.loc[:, 'Civil_Twilight'] = df_clean['Civil_Twilight'].replace({'Day': 1, 'Night': 0})
C:\Users\jmowe\AppData\Local\Temp\ipykernel_7540\2116477786.py:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals`

In [33]:
unique_values = df_clean['Sunrise_Sunset'].unique()
print(unique_values)

[0 1]


In [34]:
unique_values = df_clean['Civil_Twilight'].unique()
print(unique_values)

[0 1]


In [35]:
df_clean.shape

(3554549, 45)

In [36]:
#Looking at some unique values to better understand the data

unique_values = df_clean['Precipitation(in)'].unique()
print(unique_values)

[0.00e+00 1.00e-02 8.00e-02 5.00e-02 3.00e-02 2.00e-02 4.00e-02 1.00e-01
 1.80e-01 2.20e-01 9.00e-02 1.10e-01 1.20e-01 6.00e-02 7.00e-02 1.30e-01
 3.20e-01 1.50e-01 2.10e-01 2.40e-01 5.30e-01 9.00e-01 1.40e-01 2.00e-01
 1.90e-01 2.50e-01 2.70e-01 3.40e-01 1.70e-01 1.60e-01 5.00e-01 3.00e-01
 9.93e+00 5.50e-01 7.60e-01 2.30e-01 4.50e-01 2.60e-01 2.73e+00 6.00e-01
 2.80e-01 9.97e+00 9.95e+00 9.99e+00 2.90e-01 4.10e-01 9.98e+00 9.96e+00
 3.90e-01 4.40e-01 7.80e-01 5.40e-01 4.30e-01 5.70e-01 7.90e-01 3.70e-01
 3.30e-01 1.15e+00 5.20e-01 6.20e-01 5.10e-01 3.10e-01 7.20e-01 4.80e-01
 4.70e-01 3.50e-01 4.00e-01 9.80e-01 4.20e-01 4.60e-01 3.80e-01 7.50e-01
 1.01e+00 7.10e-01 7.70e-01 7.00e-01 3.60e-01 4.90e-01 5.60e-01 1.08e+00
 6.10e-01 6.70e-01 7.40e-01 8.90e-01 1.95e+00 9.70e-01 8.20e-01 1.07e+00
 1.39e+00 1.80e+00 6.40e-01 5.90e-01 1.19e+00 6.50e-01 1.67e+00 6.80e-01
 1.10e+00 2.05e+00 8.80e-01 1.57e+00 6.30e-01 6.60e-01 1.42e+00 1.21e+00
 9.90e-01 1.56e+00 1.11e+00 1.27e+00 1.22e+00 1.04e

In [37]:
unique_values = df_clean['Wind_Direction'].unique()
print(unique_values)

['SW' 'WSW' 'West' 'NNW' 'WNW' 'NW' 'W' 'SSW' 'East' 'SE' 'North' 'ENE'
 'NNE' 'NE' 'SSE' 'CALM' 'South' 'ESE' 'S' 'Variable' 'VAR' 'N' 'E']


In [38]:
unique_values = df_clean['Humidity(%)'].unique()
print(unique_values)

[ 58.  93.  92. 100.  96.  88.  80.  82.  86.  90.  81.  73.  77.  78.
  85.  84.  79.  68.  74.  75.  63.  57.  56.  59.  70.  71.  54.  46.
  60.  50.  65.  62.  67.  89.  69.  99.  97.  76.  87.  66.  53.   8.
  12.  15.  23.  24.  39.  51.  36.  38.  83.  40.  22.   6.  48.  49.
  42.  10.  37.  45.  44.  31.  64.  94.  34.  72.  43.  55.  14.  30.
  21.  18.  19.  91.  98.  47.  95.  41.  61.  52.  33.  32.  28.  27.
  35.   9.  20.  25.  17.  16.  13.  11.  26.  29.   7.   5.   4.   3.
   2.   1.]


In [40]:
#Exporting the cleaned data


df_clean.to_csv(os.path.join(path, 'Data','df_clean.csv'))

In [41]:
unique_values = df_clean['State'].unique()
print(unique_values)

['OH' 'IN' 'KY' 'WV' 'PA' 'MI' 'CA' 'MN' 'LA' 'NE' 'MO' 'IA' 'ND' 'CO'
 'KS' 'TX' 'WI' 'OK' 'WY' 'SD' 'MS' 'AR' 'IL' 'MA' 'RI' 'ME' 'NY' 'TN'
 'FL' 'MD' 'NC' 'GA' 'VA' 'CT' 'NJ' 'DE' 'NH' 'SC' 'VT' 'DC' 'AL' 'MT'
 'ID' 'UT' 'AZ' 'NM' 'NV' 'WA' 'OR']


NameError: name 'unique_values' is not defined